# Generated by Django 5.2.1 on 2025-06-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_market_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restock_level',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='market',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
