# Generated by Django 5.2.1 on 2025-05-12 18:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name': "Do'kon", 'verbose_name_plural': "Do'konlar"},
        ),
        migrations.AddField(
            model_name='market',
            name='address',
            field=models.TextField(blank=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='market',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Yaratilgan Sana'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='market',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Do'kon Nomi"),
        ),
        migrations.AlterField(
            model_name='market',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
